<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.snowdrift</groupId>
        <artifactId>snowdrift-cache</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>snowdrift-cache-redis</artifactId>
    <description>Snowdrift Cache Redis — 基于 RedisTemplate 的缓存实现</description>

    <dependencies>
        <dependency>
            <groupId>com.snowdrift</groupId>
            <artifactId>snowdrift-cache-base</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
    </dependencies>
</project>
