spring:
  redis:
    host: 192.168.1.220
    port: 6379
    password: YunK0ng
    database: 1
snowdrift:
  doc:
    knife4j:
      enabled: true
      title: 测试服务接口文档
      description: 测试服务接口文档
      website: http://localhost:8080/swagger-ui.html
      base-package: com.snowdrift.test.controller
      version: v1